name: Check Conventions

on:
  push:
  pull_request:

jobs:
  check:
    uses: OpenAEC-Foundation/RepoCleaner/.github/workflows/check-conventions.yml@master
    with:
      repo_name: ${{ github.event.repository.name }}
      org: OpenAEC-Foundation
    secrets:
      gh_token: ${{ secrets.CONVENTION_ENFORCER_TOKEN }}
